Feature: validating Demo QA forms

Scenario: filling the form
Given user is on chrome
When filling the form firstname and lastname and email
|firstname|lastname|email|
|aravinth|venkat|aravin@gmail.com|


Scenario: filling the form
Given user is on chrome
When filling the form firstname and lastname and email
|firstname|lastname|email|
|aravinth|venkat|aravin@gmail.com|


Scenario: filling the form
Given user is on chrome
When filling the form firstname and lastname and email
|firstname|lastname|email|
|aravinth|venkat|aravin@gmail.com|

